// This file is "model.dart"
import 'package:dart_mappable/dart_mappable.dart';

// Will be generated by dart_mappable
part 'verify_response.mapper.dart';

@MappableClass()
class VerifyResponse with VerifyResponseMappable {
  final String token;
  final String refresh;
  final String id;

  VerifyResponse(this.id, this.refresh, this.token);
}
