// This file is "model.dart"
import 'package:dart_mappable/dart_mappable.dart';
import 'package:kinder_app/features/authentication/domain/entities/auth_entity.dart';

// Will be generated by dart_mappable
part 'auth_model.mapper.dart';

@MappableClass()
class AuthModel extends AuthEntity with AuthModelMappable {
  AuthModel({required super.token, required super.refresh});
}
